### ISSUE TITLE
Error Importing

### ISSUE THREAD

**Issue by metahipster** [DragonBones/DesignPanel#1]
I tried importing with the default settings; it didnt' work because my bitmaps were 528px high each (there were 4) and the texture packer didn't have enough real estate within the default 512px height. 

however, the error dialogs were very confusing and ultimately locked up the panel.

RangeError: Error #1125: The index 1 is out of range 1.  (BUTTON IN ASIAN CHARACTERS)
After clicking the only button, the following dialog was also entirely in asian characters so I'm afraid I can't type it in here.

Thanks!

**Comment by fans8** [comment]
Hi metahipster,
I will check the issue and give you the feedback ASAP.

2012/11/17 metahipster notifications@github.com

**Comment by superlancelot** [comment]
Hi metahipster,
Did you use the latest version of design panel? In the latest version of design panel, the default value of texture size is "AutoSize". Please choose "AutoSize" and try again:)
