### ISSUE TITLE
After addind new animations: RangeError: Error #1125: L'index 1 est en dehors des limites 1.

### ISSUE THREAD

**Issue by BenoitFreslon** [DragonBones/DesignPanel#11]
Hello,

I'm using the last version of DragonBones Panel but I have an error when I try to import my item.

I'm usgin this default settings:
![spgfupg](https://cloud.githubusercontent.com/assets/758680/2861295/42e5e536-d1dc-11e3-9ba1-9185b3873953.png)

And I got this error:
![capture_20140502_001](https://cloud.githubusercontent.com/assets/758680/2861297/4a9ed6e8-d1dc-11e3-8caf-8ddb7617e116.png)

I don't have this error on other .fla.

Here the .fla
https://dl.dropboxusercontent.com/u/34379764/Partage/craven.fla

Thanks.

**Comment by akdcl** [comment]
Thanks.
The bug has been fixed in dev branch.

https://github.com/DragonBones/SkeletonAnimationDesignPanel/commit/e65f85a7a99ef96da0f20a75d9caeb094245a767

**Comment by BenoitFreslon** [comment]
Hello,

Thanks for you quick feedback.

But How to build a .zxp file with this sources?

Thanks.
