### ISSUE TITLE
DragonBonesDesignPanel.zxp2.4.1不支持flash cc 2014

### ISSUE THREAD

**Issue by pilihou** [DragonBones/DesignPanel#13]
DragonBonesDesignPanel.zxp2.4.1不支持flash cc 2014

**Comment by zrong** [comment]
我就是用的flash cc，可以支持。

**Comment by pilihou** [comment]
flash cc 2014可以安装，原来是extension manager cc之前不支持flash cc 2014，今早更新到7.2.1.6就支持了
