### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by bigstupidx** [DragonBones/DesignPanel#2]
到底怎么导入啊？，给的样例导入都没有问题，为什么自己新建了一个fla，加了两张图，但是导入的时候却显示：
“ReferenceError: Error #1069: 在 flash.display.AVM1Movie 上找不到属性 getChildAt，且没有默认值。”

是需要用模板创建还是需要什么jsfl什么的？，新手完全不会啊。。

**Comment by bigstupidx** [comment]
再次点import的时候又显示“Cannot find any skeleton item in the library of Fla XXXX”，求神牛们指导一下啊。。

**Comment by akdcl** [comment]
你好，看看这些能不能帮上你：
1、动画的fla源码需要使用as3
2、动画的fla源码发布flash player版本不能低于10.2
3、需要导入的fla文档需要处于选中激活状态

**Comment by bigstupidx** [comment]
谢谢，原来是需要as3，我默认设置的是as2，非常感谢！
