### ISSUE TITLE
关键帧缓动功能在3.0Panel中被去掉了

### ISSUE THREAD

**Issue by lizistorm** [DragonBones/DesignPanel#20]
动画师在制作动画时有这个全局调整缓动的功能比较方便：
在flash里看不到骨骼联动关系，在panel里全局调整可以看到大概效果，然后去flash里面精调；
一些简单的动画可以直接在panel里设置全局缓动；

**Comment by akdcl** [comment]
全局缓动被去掉了，需要的缓动需要在flash pro的补间上设置
