### ISSUE TITLE
Advanced Option not saved

### ISSUE THREAD

**Issue by urunky** [DragonBones/DesignPanel#26]
Skeleton Data Name is saved but 
Skeleton Data File Name
Texture Data File Name
Texture File Name 
is not saved.

**Comment by akdcl** [comment]
Thanks, the bug has been fixed in dev branch

**Comment by urunky** [comment]
Thanks a lot. Would you plz update the zxp either?

**Comment by akdcl** [comment]
The zxp has been updated in dev branch.
https://github.com/DragonBones/DesignPanel/blob/dev/DragonBonesDesignPanel.zxp
