### ISSUE TITLE
Can't open panel again after Flash crash

### ISSUE THREAD

**Issue by vrobel** [DragonBones/DesignPanel#3]
Flash Pro (CS6) crashed and I can't reopen the DragonBones Design Panel. I only see something like this. Looks like an error while initializing Design Panel. Wondering if panel configuration is stored in a Shared Object and it might get broken. If yes, do yo know where is that shared object stored?
![image](https://f.cloud.github.com/assets/174956/15597/ee6a129a-4797-11e2-96d6-fd16dd466bef.png)

**Comment by vrobel** [comment]
Ok. After a restart it got back working again (so just a note for the future)

**Comment by superlancelot** [comment]
It has been fixed in V2.1

**Comment by naviator** [comment]
I have similar issue with Flash Pro CS6 and DragonBones v 2.4.1 - cannot open design panel in Mac OS X, application is not responding.
![screen shot 2014-02-03 at 15 46 05](https://f.cloud.github.com/assets/1632532/2065472/045db396-8ce2-11e3-869b-d9443795206e.png)

**Comment by superlancelot** [comment]
Would you give more detail about the issue? DragonBones DesignPanel make FlashPro no respond?
