### ISSUE TITLE
Add linux support ?

### ISSUE THREAD

**Issue by Geequlim** [DragonBones/DesignPanel#31]
As there are a lot of game developers like working on this platform with our favorite tools.

**Comment by rawsp33d** [comment]
👍 All my research made me believe Dragonbones would be a good alternative to spine/sprinter, until I realized it doesn't have a Linux build :-(

**Comment by manuelsongokuh** [comment]
me too!!!

**Comment by manuelsongokuh** [comment]
news for port in linux ?

**Comment by tushantin** [comment]
Message from the future. I would love to have a Linux port too!

**Comment by Crispinophur** [comment]
I know that it is ActionScript thingy related, but... Linux port somehow will be really appreciated.

**Comment by drtwisted** [comment]
Would love to have linux support as well!

**Comment by boehm-e** [comment]
![image](https://user-images.githubusercontent.com/11290215/47080411-3248c000-d208-11e8-9743-a51fb1108521.png)

Using wine, and by downloading the exe from their website, the animation software is working perfectly

**Comment by drtwisted** [comment]
@boehm-e thanks, people here are asking for native support, though. Wine is always an option, for sure, but more of a workaround then a clear solution.

**Comment by boehm-e** [comment]
@drtwisted Yes, i understand that, but as it is working realy well, and realy quickly, i just wanted to let other people know

**Comment by StuckUpCreations** [comment]
> @drtwisted Yes, i understand that, but as it is working realy well, and realy quickly, i just wanted to let other people know

some of us stay away from wine, for the same reason we use linux and not windoze..

**Comment by roracle** [comment]
I need this on Linux, please!  I might go over the build instructions and compile it myself if possible, as well.

**Comment by wolewd** [comment]
still waiting for linux support ;)

**Comment by saricden** [comment]
2022 here, Linux support would be reeeeeally nice :pray:

**Comment by Geequlim** [comment]
It seems not possile any more.

**Comment by GuerreiroLeonardo** [comment]
Still waiting

**Comment by TiarSukaCoding** [comment]
yes we need linux build!

**Comment by ghost** [comment]
Even in 2024 we are waiting!

**Comment by Haruki-Hotarou-2021** [comment]
I want a linux support!!!!!

**Comment by avalel** [comment]
Going to beg for dragonbones Linux build once more

**Comment by faraggi** [comment]
Leaving a comment to add support for this.
Is there any technical reason this isn't being implemented?

**Comment by ajskfjalsdjfl** [comment]
Hope is the last thing to be lost

**Comment by AbiPasundan** [comment]
It's 2026 and still no linux support(^-^)

**Comment by unib14z3** [comment]
Why was this issue closed even though there was no support?
