### ISSUE TITLE
Error Importing Selected Items in Windows 64 bit

### ISSUE THREAD

**Issue by Sudarmin** [DragonBones/DesignPanel#4]
When I tried to import "Selected Items" using the "SkeletonAnimationDesignPanel" it showed an error "Cannot find any skeleton item in the library of Fla The following JavaScript error(s) occurred:

TypeError: _frame.elements has no properties
!"

I tried this in 4 computers, 2 are 32-bit windows computer, 2 are 64-bit windows computer, all the 32-bit computers can import while the others cannot, would the problem be the 64-bit or maybe something else?

**Comment by superlancelot** [comment]
Would you send your fla to us? I also use 64-bit computer usually.
Our email is dragonbonesteam@gmail.com

**Comment by Sudarmin** [comment]
I still use the Tutorial Fla which is : DragonBones_tutorial_Start.fla
I use windows 7 64 bit, it does not work I don't know why, but it works on other windows 7 32 bit

I added a video to youtube to give example how this happened :
http://www.youtube.com/watch?v=Q6UhQ8EnNKY&feature=youtu.be

It's a little blurry, but I will send it to you the video to your email

**Comment by Sudarmin** [comment]
Hi, I found out the culprit, it was the Pixel Tools extension, I disabled it, and the dragonbones works, Thank God!
For anyone who has the same problem as me, try to disable one by one the extensions that you have, for me it was the "Pixel Tools v2.0.0.0 made by Patrick Mineault"
