### ISSUE TITLE
怎么导入工程生成zxp文件?

### ISSUE THREAD

**Issue by haoap** [DragonBones/DesignPanel#5]
我用FlashBuilder4新建了Flex Porject,导入了SkeletonAnimationLibrary.swc之后直接编译的话会有Unable to resolve resource bundle "resources" for locale "en_US".   的错误.
加入 source-path=./locale/{locale} 之后变成一个警告,但是能便已过了.
看bin-debug下有一堆文件生成了,但是还是不知道怎么生成zxp文件?
而且我点debug还是不能运行.
麻烦能介绍下怎么生成zxp文件吗?
新手问题,不胜感激!

**Comment by akdcl** [comment]
你好，附加编译参数“-locale en_US zh_CN ja_JP fr_FR -source-path ./locale/{locale} -allow-source-path-overlap=true -default-size 720 480 -default-script-limits 256 180”，将release之后的swf放到build文件夹下，双击.mxi文件可以打包成zxp文件（mxi会启动Adobe Extension Manager打包），关于debug，如果已经在bin-debug文件夹下生成了文件，说明debug已经成功了

**Comment by haoap** [comment]
非常感谢!
编译通过,也能和cs debug了.
但是有个问题,我做成的release下面好多.swz文件,
做成的安装包装完后点出SkeletonAnimationDesignPanel一片空白,什么都没有.请问知道这是什么原因吗.
谢谢.
下面是我release下面的文件列表.
advancedgrids_4.6.0.23201.swz
charts_4.6.0.23201.swz
framework_4.6.0.23201.swz
mx_4.6.0.23201.swz
osmf_1.0.0.16316.swz
playerProductInstall.swf
rpc_4.6.0.23201.swz
SkeletonAnimationDesignPanel.html
SkeletonAnimationDesignPanel.swf
sparkskins_4.6.0.23201.swz
spark_4.6.0.23201.swz
spark_dmv_4.6.0.23201.swz
swfobject.js
textLayout_2.0.0.232.swz

**Comment by akdcl** [comment]
需要修改：项目属性>Flex构建路径>库路径>框架链接:合并到代码中
另外SkeletonAnimationDesignPanel一片空白，有可能是release的时候没有成功，具体原因也不太清楚，可以尝试多release几次

**Comment by haoap** [comment]
谢谢,解决了.
